# Default hand strings - can be used in specific or random order

DEFAULT_HANDS = {
    "royal_flush"               : "10C,JC,QC,KC,AC",
    "royal_flush_2"             : "10D,JD,QD,KD,AD",
    "royal_flush_unsorted"      : "KD,QD,AD,10D,JD",
    "straight_flush"            : "9S,10S,JS,QS,KS",
    "straight_flush_ace_low"    : "2H,3H,4H,5H,AH",
    "straight_flush_numbers"    : "5C,6C,8C,7C,9C",
    "straight_flush_2"          : "9D,10D,JD,QD,KD",
    "four_of_a_kind"            : "4C,4D,4H,4S,5C",
    "four_of_a_kind_5s"         : "5C,5D,5H,5S,6C",
    "full_house"                : "QC,QD,QS,JH,JS",
    "full_house_less"           : "JC,JD,JS,10H,10S",
    "flush"                     : "AS,JS,9S,8S,2S",
    "flush_less"                : "KS,QS,10S,7S,6S",
    "straight"                  : "5S,6C,7D,8H,9S",
    "straight_ace_low"          : "AC,2D,3C,4H,5S",
    "three_of_a_kind"           : "7H,7C,7D,2S,2D",
    "two_pair"                  : "9C,9H,7C,7H,2S",
    "two_pair_less"             : "8D,8S,6C,6S,3H",
    "pair"                      : "JS,JD,5C,6H,9D",
    "pair_less"                 : "10S,10D,5H,6C,9H",
    "high_card"                 : "KS,JD,9S,5H,4H",
    "high_card_less"            : "QS,10D,8S,3H,2H",

    # Wikipedia testcases
    "wp_straight_flush_1"       : "7H,6H,5H,4H,3H",
    "wp_straight_flush_2"       : "5S,4S,3S,2S,AS",
    "wp_straight_flush_3"       : "JC,10C,9C,8C,7C",
    "wp_straight_flush_4"       : "JD,10D,9D,8D,7D",
    "wp_four_of_a_kind_1"       : "10C,10D,10H,10S,5D",
    "wp_four_of_a_kind_2"       : "6D,6H,6S,6C,KS",
    "wp_four_of_a_kind_3"       : "10C,10D,10H,10S,QC",
    "wp_four_of_a_kind_4"       : "10C,10D,10H,10S,5D",
}
